"""empty message

Revision ID: 19e5c256d192
Revises: c067f5c9ea26
Create Date: 2026-08-19 21:19:42.183630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19e5c256d192'
down_revision = 'c067f5c9ea26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('event', schema=None) as batch_op:
    #     batch_op.alter_column('pick_deadline',
    #            existing_type=sa.DATETIME(),
    #            nullable=False)

    with op.batch_alter_table('song', schema=None) as batch_op:
        # batch_op.alter_column('pick_num',
        #        existing_type=sa.INTEGER(),
        #        nullable=False)
        # batch_op.alter_column('pick_time',
        #        existing_type=sa.DATETIME(),
        #        nullable=False)
        # batch_op.alter_column('approved',
        #        existing_type=sa.VARCHAR(length=256),
        #        nullable=False)
        batch_op.drop_index(batch_op.f('ix_song_artist'))
        batch_op.create_index(batch_op.f('ix_song_artist'), ['artist'], unique=False)
        batch_op.drop_index(batch_op.f('ix_song_link'))
        batch_op.create_index(batch_op.f('ix_song_link'), ['link'], unique=False)
        batch_op.drop_index(batch_op.f('ix_song_title'))
        batch_op.create_index(batch_op.f('ix_song_title'), ['title'], unique=False)

    # with op.batch_alter_table('vote', schema=None) as batch_op:
    #     batch_op.alter_column('is_tiebreaker',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.alter_column('is_tiebreaker',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_song_title'))
        batch_op.create_index(batch_op.f('ix_song_title'), ['title'], unique=1)
        batch_op.drop_index(batch_op.f('ix_song_link'))
        batch_op.create_index(batch_op.f('ix_song_link'), ['link'], unique=1)
        batch_op.drop_index(batch_op.f('ix_song_artist'))
        batch_op.create_index(batch_op.f('ix_song_artist'), ['artist'], unique=1)
        batch_op.alter_column('approved',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('pick_time',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('pick_num',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('pick_deadline',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
