"""vote is_tiebreaker field

Revision ID: 28006d6eaf3e
Revises: cb7f72ce4fa2
Create Date: 2026-08-18 18:13:23.489437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28006d6eaf3e'
down_revision = 'cb7f72ce4fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.alter_column('next_match_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_tiebreaker', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_column('is_tiebreaker')

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.alter_column('next_match_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
