"""nullable approval msg

Revision ID: 35433b588ab3
Revises: a290275b0dfd
Create Date: 2026-08-20 02:24:03.635693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35433b588ab3'
down_revision = 'a290275b0dfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.alter_column('approval_message',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.alter_column('approval_message',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)

    # ### end Alembic commands ###
