"""approval message

Revision ID: 68d5ba3c565f
Revises: 19e5c256d192
Create Date: 2026-08-19 22:27:54.189941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68d5ba3c565f'
down_revision = '19e5c256d192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('event', schema=None) as batch_op:
    #     batch_op.alter_column('pick_deadline',
    #            existing_type=sa.DATETIME(),
    #            nullable=False)

    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_message', sa.String(length=1024), nullable=True))
        # batch_op.alter_column('pick_num',
        #        existing_type=sa.INTEGER(),
        #        nullable=False)
        # batch_op.alter_column('pick_time',
        #        existing_type=sa.DATETIME(),
        #        nullable=False)
        # batch_op.alter_column('approved',
        #        existing_type=sa.VARCHAR(length=256),
        #        nullable=False)

    # with op.batch_alter_table('vote', schema=None) as batch_op:
    #     batch_op.alter_column('is_tiebreaker',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.alter_column('is_tiebreaker',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.alter_column('approved',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('pick_time',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('pick_num',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('approval_message')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('pick_deadline',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
