"""event pick_deadline, song pick_time

Revision ID: 8efc21d8c0d8
Revises: 9ef5a6c751fa
Create Date: 2026-08-19 20:27:01.351957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8efc21d8c0d8'
down_revision = '9ef5a6c751fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('event', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('pick_deadline', sa.DateTime(), nullable=True))

    with op.batch_alter_table('song', schema=None) as batch_op:
         batch_op.add_column(sa.Column('pick_time', sa.DateTime(), nullable=True))
    #     batch_op.alter_column('pick_num',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    #     batch_op.alter_column('approved',
    #            existing_type=sa.VARCHAR(length=256),
    #            nullable=False)

    # with op.batch_alter_table('vote', schema=None) as batch_op:
    #     batch_op.alter_column('is_tiebreaker',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False)
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.alter_column('is_tiebreaker',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.alter_column('approved',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('pick_num',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('pick_time')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('pick_deadline')

    # ### end Alembic commands ###
