"""empty message

Revision ID: 9ef5a6c751fa
Revises: 28006d6eaf3e
Create Date: 2026-08-19 19:37:12.976502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ef5a6c751fa'
down_revision = '28006d6eaf3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('song', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('pick_num', sa.Integer(), nullable=False))
    #     batch_op.add_column(sa.Column('approved', sa.String(length=256), nullable=False))
    #     batch_op.create_index(batch_op.f('ix_song_approved'), ['approved'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_song_pick_num'), ['pick_num'], unique=False)

    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.alter_column('is_tiebreaker',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.alter_column('is_tiebreaker',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_song_pick_num'))
        batch_op.drop_index(batch_op.f('ix_song_approved'))
        batch_op.drop_column('approved')
        batch_op.drop_column('pick_num')

    # ### end Alembic commands ###
