"""first commit

Revision ID: babd1300e3f1
Revises: 
Create Date: 2026-08-17 02:22:37.492494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'babd1300e3f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_slug', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_event_slug'), ['event_slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_event_name'), ['name'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('round',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('round_slug', sa.String(length=256), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('round', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_round_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_round_round_slug'), ['round_slug'], unique=False)

    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('link', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_song_artist'), ['artist'], unique=True)
        batch_op.create_index(batch_op.f('ix_song_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_link'), ['link'], unique=True)
        batch_op.create_index(batch_op.f('ix_song_title'), ['title'], unique=True)
        batch_op.create_index(batch_op.f('ix_song_user_id'), ['user_id'], unique=False)

    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['round.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_round_id'), ['round_id'], unique=False)

    op.create_table('candidate',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.PrimaryKeyConstraint('song_id', 'match_id')
    )
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_song_id'), ['song_id'], unique=False)

    op.create_table('vote',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('match_id', 'user_id'),
    sa.UniqueConstraint('match_id', 'user_id', name='vote once per match')
    )
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vote_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vote_song_id'), ['song_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vote_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vote_user_id'))
        batch_op.drop_index(batch_op.f('ix_vote_song_id'))
        batch_op.drop_index(batch_op.f('ix_vote_match_id'))

    op.drop_table('vote')
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_song_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_match_id'))

    op.drop_table('candidate')
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_round_id'))

    op.drop_table('match')
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_song_user_id'))
        batch_op.drop_index(batch_op.f('ix_song_title'))
        batch_op.drop_index(batch_op.f('ix_song_link'))
        batch_op.drop_index(batch_op.f('ix_song_event_id'))
        batch_op.drop_index(batch_op.f('ix_song_artist'))

    op.drop_table('song')
    with op.batch_alter_table('round', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_round_round_slug'))
        batch_op.drop_index(batch_op.f('ix_round_event_id'))

    op.drop_table('round')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_name'))
        batch_op.drop_index(batch_op.f('ix_event_event_slug'))

    op.drop_table('event')
    # ### end Alembic commands ###
