"""event pick_deadline, song pick_time

Revision ID: c067f5c9ea26
Revises: 8efc21d8c0d8
Create Date: 2026-08-19 20:30:00.350885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c067f5c9ea26'
down_revision = '8efc21d8c0d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('_alembic_tmp_song')
    # with op.batch_alter_table('event', schema=None) as batch_op:
    #     batch_op.alter_column('pick_deadline',
    #            existing_type=sa.DATETIME(),
    #            nullable=False)

    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pick_time', sa.DateTime(), nullable=True))
    #     batch_op.alter_column('pick_num',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    #     batch_op.alter_column('approved',
    #            existing_type=sa.VARCHAR(length=256),
    #            nullable=False)

    # with op.batch_alter_table('vote', schema=None) as batch_op:
    #     batch_op.alter_column('is_tiebreaker',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.alter_column('is_tiebreaker',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.alter_column('approved',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('pick_num',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('pick_time')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('pick_deadline',
               existing_type=sa.DATETIME(),
               nullable=True)

    op.create_table('_alembic_tmp_song',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('event_id', sa.INTEGER(), nullable=False),
    sa.Column('artist', sa.VARCHAR(length=256), nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), nullable=False),
    sa.Column('link', sa.VARCHAR(length=256), nullable=False),
    sa.Column('pick_num', sa.INTEGER(), nullable=False),
    sa.Column('approved', sa.VARCHAR(length=256), nullable=False),
    sa.Column('pick_time', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_song_event_id_event')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_song_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_song'))
    )
    # ### end Alembic commands ###
