"""add prev_match relationship

Revision ID: cb7f72ce4fa2
Revises: babd1300e3f1
Create Date: 2026-08-18 16:19:03.335281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb7f72ce4fa2'
down_revision = 'babd1300e3f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_match_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_match_next_match_id'), ['next_match_id'], unique=False)
        batch_op.create_foreign_key(None, 'match', ['next_match_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_match_next_match_id'))
        batch_op.drop_column('next_match_id')

    # ### end Alembic commands ###
